# Generated by Django 3.2.5 on 2021-12-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('mmr', models.IntegerField()),
                ('idade', models.IntegerField()),
                ('email', models.CharField(max_length=80)),
                ('hash_senha', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField()),
                ('p2', models.IntegerField()),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('tempo_s', models.IntegerField()),
            ],
        ),
    ]
